configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cpeg82230457acr.azurecr.io/82230457
  newTag: "202410130937"
- name: cpeg82230457acr.azurecr.io/cloud-sample
  newTag: "202408120727"
